language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ralbuquerque95/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ralbuquerque95/react-test npm test -- --coverage

after_success:
  - docker build -t ralbuquerque95/multi-client ./client
  - docker build -t ralbuquerque95/multi-nginx ./nginx
  - docker build -t ralbuquerque95/multi-server ./server
  - docker build -t ralbuquerque95/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker HUB
  - docker push ralbuquerque95/multi-client
  - docker push ralbuquerque95/multi-nginx
  - docker push ralbuquerque95/multi-server
  - docker push ralbuquerque95/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-201625974130"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
